display_information:
  name: Zoe
  description: Content & Social Media
  background_color: "#000000"
features:
  bot_user:
    display_name: Zoe
    always_online: true
oauth_config:
  scopes:
    bot:
      - app_mentions:read
      - canvases:read
      - canvases:write
      - channels:history
      - channels:read
      - chat:write
      - groups:history
      - groups:read
      - im:history
      - im:read
      - im:write
      - mpim:read
      - reactions:read
      - reactions:write
settings:
  event_subscriptions:
    bot_events:
      - app_mention
      - message.channels
      - message.groups
      - message.im
      - reaction_added
  interactivity:
    is_enabled: true
  org_deploy_enabled: false
  socket_mode_enabled: true
  token_rotation_enabled: false
